- name: Install Apache Web Server
  hosts: vm3
  become: yes  # Use 'become' to execute tasks with sudo
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu servers
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Time in seconds the apt cache is considered valid

    - name: Install Apache2
      apt:
        name: apache2
        state: present  # Ensure Apache is installed

    - name: Ensure Apache is running and enabled on boot
      systemd:
        name: apache2
        state: started
        enabled: yes